/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package initGame;

import Objects.ListaOggetti;
import Objects.Oggetto;
import static Players.DatabaseScore.GetScores;
import static Players.DatabaseScore.InsertScore;
import Players.Player;
import static Players.Saves.CaricaSalvataggio;
import static Players.Saves.PreparaSalvataggio;
import static Players.Saves.Salvataggi;
import static Players.Saves.salvaGiocatore;
import Players.Score;
import Rooms.FinalRoom;
import Rooms.Room;
import Rooms.ListaRooms;
import static initGame.inizializzaGame.CaricaStanze;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static outputGame.Answers.Help;
import static outputGame.Answers.noRoom;
import outputGame.takeThread;
import static outputGame.testoGame.leggiFinalRoom;
import static outputGame.testoGame.leggiOggetti;
import static outputGame.testoGame.leggiRegole;



/**
 *
 * @author Leonardo
 */
public class SwingMain extends javax.swing.JFrame {
     
     private static Player Giocatore;
     private static List<Room> Stanze= new ArrayList<>() ;
     private static List<Oggetto> lista_items= new ArrayList<>();
     private static  String[] regole= new String[15];
     private static FinalRoom finalr= new FinalRoom();
     private static ListaOggetti items= new ListaOggetti();
     int row_regole;
    /**
     * Creates new form SwingMain
     * @throws java.io.FileNotFoundException
     */
    public SwingMain() throws FileNotFoundException, IOException {
        
      
      ListaRooms mapGame= new ListaRooms();
 
     
      

        initComponents();
        CaricaStanze(mapGame);
        items = leggiOggetti();
        finalr = leggiFinalRoom();
        
         row_regole = leggiRegole(regole);
        lista_items= items.getOggetti();
        Stanze =  mapGame.getRooms();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GameJFrame = new javax.swing.JFrame();
        TextFieldGame = new javax.swing.JTextField();
        NordButton = new javax.swing.JButton();
        OvestButton = new javax.swing.JButton();
        EstButton = new javax.swing.JButton();
        SudButton = new javax.swing.JButton();
        TakeiButton = new javax.swing.JButton();
        UseButton = new javax.swing.JButton();
        InventoryButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        Nickname = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaGame = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        TutorialJFrame = new javax.swing.JFrame();
        HomeButton_Tutorial = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TutorialTextArea = new javax.swing.JTextArea();
        CreatorsJFrame = new javax.swing.JFrame();
        HomeButton = new javax.swing.JButton();
        Sviluppatore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FinalRoomJFrame = new javax.swing.JFrame();
        FinalInput = new javax.swing.JTextField();
        FinalButton = new javax.swing.JButton();
        NicknameFinal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FinalTextArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        ScoreJFrame = new javax.swing.JFrame();
        jScrollPane6 = new javax.swing.JScrollPane();
        ScoreTextArea = new javax.swing.JTextArea();
        WinLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        HomeButton_Score = new javax.swing.JButton();
        SavesJFrame = new javax.swing.JFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        SavesTextArea = new javax.swing.JTextArea();
        SaveField = new javax.swing.JTextField();
        AvviaJButton = new javax.swing.JButton();
        HomeButton_Saves = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        SavesButton = new javax.swing.JButton();
        SviluppatoriButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ID = new javax.swing.JTextPane();
        RulesButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        GameJFrame.setMinimumSize(new java.awt.Dimension(653, 522));
        GameJFrame.setSize(new java.awt.Dimension(653, 522));

        TextFieldGame.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TextFieldGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldGameActionPerformed(evt);
            }
        });

        NordButton.setText("N");
        NordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NordButtonActionPerformed(evt);
            }
        });

        OvestButton.setText("O");
        OvestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OvestButtonActionPerformed(evt);
            }
        });

        EstButton.setText("E");
        EstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstButtonActionPerformed(evt);
            }
        });

        SudButton.setText("S");
        SudButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SudButtonActionPerformed(evt);
            }
        });

        TakeiButton.setText("Prendi");
        TakeiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TakeiButtonActionPerformed(evt);
            }
        });

        UseButton.setText("Usa");
        UseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseButtonActionPerformed(evt);
            }
        });

        InventoryButton.setText("Inventario");
        InventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Salva");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        HelpButton.setText("Help");
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        Nickname.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        Nickname.setForeground(new java.awt.Color(0, 102, 255));
        Nickname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nickname.setText("  ");

        TextAreaGame.setEditable(false);
        TextAreaGame.setColumns(20);
        TextAreaGame.setFont(new java.awt.Font("DejaVu Sans Light", 1, 14)); // NOI18N
        TextAreaGame.setRows(5);
        jScrollPane2.setViewportView(TextAreaGame);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));

        javax.swing.GroupLayout GameJFrameLayout = new javax.swing.GroupLayout(GameJFrame.getContentPane());
        GameJFrame.getContentPane().setLayout(GameJFrameLayout);
        GameJFrameLayout.setHorizontalGroup(
            GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameJFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(GameJFrameLayout.createSequentialGroup()
                        .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GameJFrameLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NordButton)
                                    .addComponent(SudButton)))
                            .addComponent(Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GameJFrameLayout.createSequentialGroup()
                                .addGap(442, 442, 442)
                                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(UseButton)
                                    .addComponent(TakeiButton)
                                    .addComponent(InventoryButton)))
                            .addGroup(GameJFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OvestButton)
                                    .addGroup(GameJFrameLayout.createSequentialGroup()
                                        .addGap(472, 472, 472)
                                        .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(GameJFrameLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldGame, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(28, 28, 28))
            .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE))
        );
        GameJFrameLayout.setVerticalGroup(
            GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameJFrameLayout.createSequentialGroup()
                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameJFrameLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameJFrameLayout.createSequentialGroup()
                        .addContainerGap(26, Short.MAX_VALUE)
                        .addComponent(Nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(TextFieldGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UseButton)
                    .addComponent(NordButton))
                .addGap(14, 14, 14)
                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EstButton)
                    .addComponent(OvestButton)
                    .addComponent(TakeiButton))
                .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameJFrameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SudButton))
                    .addGroup(GameJFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(InventoryButton)))
                .addGap(80, 80, 80))
            .addGroup(GameJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        String nick = ID.getText();Nickname.setText(nick);

        TutorialJFrame.setMinimumSize(new java.awt.Dimension(673, 500));

        HomeButton_Tutorial.setText("Home");
        HomeButton_Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton_TutorialActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\\\img\\regole.jpg"));

        TutorialTextArea.setEditable(false);
        TutorialTextArea.setColumns(20);
        TutorialTextArea.setFont(new java.awt.Font("DejaVu Sans Light", 1, 14)); // NOI18N
        TutorialTextArea.setRows(5);
        jScrollPane4.setViewportView(TutorialTextArea);

        javax.swing.GroupLayout TutorialJFrameLayout = new javax.swing.GroupLayout(TutorialJFrame.getContentPane());
        TutorialJFrame.getContentPane().setLayout(TutorialJFrameLayout);
        TutorialJFrameLayout.setHorizontalGroup(
            TutorialJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialJFrameLayout.createSequentialGroup()
                .addGroup(TutorialJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TutorialJFrameLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(HomeButton_Tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TutorialJFrameLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(TutorialJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
        );
        TutorialJFrameLayout.setVerticalGroup(
            TutorialJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TutorialJFrameLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(HomeButton_Tutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(TutorialJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        CreatorsJFrame.setMinimumSize(new java.awt.Dimension(673, 500));

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        Sviluppatore.setFont(new java.awt.Font("DejaVu Sans Light", 1, 24)); // NOI18N
        Sviluppatore.setForeground(new java.awt.Color(255, 255, 0));
        Sviluppatore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\sviluppatori.jpg"));

        javax.swing.GroupLayout CreatorsJFrameLayout = new javax.swing.GroupLayout(CreatorsJFrame.getContentPane());
        CreatorsJFrame.getContentPane().setLayout(CreatorsJFrameLayout);
        CreatorsJFrameLayout.setHorizontalGroup(
            CreatorsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatorsJFrameLayout.createSequentialGroup()
                .addGroup(CreatorsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatorsJFrameLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreatorsJFrameLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(Sviluppatore, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(CreatorsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
        );
        CreatorsJFrameLayout.setVerticalGroup(
            CreatorsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatorsJFrameLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(Sviluppatore, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(CreatorsJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreatorsJFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)))
        );

        FinalRoomJFrame.setMinimumSize(new java.awt.Dimension(673, 500));

        FinalInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalInputActionPerformed(evt);
            }
        });

        FinalButton.setText("Invia");
        FinalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalButtonActionPerformed(evt);
            }
        });

        NicknameFinal.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        NicknameFinal.setForeground(new java.awt.Color(0, 102, 255));

        FinalTextArea.setEditable(false);
        FinalTextArea.setColumns(20);
        FinalTextArea.setFont(new java.awt.Font("DejaVu Sans Light", 1, 14)); // NOI18N
        FinalTextArea.setRows(5);
        jScrollPane3.setViewportView(FinalTextArea);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\finalroom.jpg"));

        javax.swing.GroupLayout FinalRoomJFrameLayout = new javax.swing.GroupLayout(FinalRoomJFrame.getContentPane());
        FinalRoomJFrame.getContentPane().setLayout(FinalRoomJFrameLayout);
        FinalRoomJFrameLayout.setHorizontalGroup(
            FinalRoomJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                .addGroup(FinalRoomJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(NicknameFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(FinalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(FinalButton)))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(FinalRoomJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
        );
        FinalRoomJFrameLayout.setVerticalGroup(
            FinalRoomJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NicknameFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(FinalInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(FinalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(FinalRoomJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FinalRoomJFrameLayout.createSequentialGroup()
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        ScoreJFrame.setMinimumSize(new java.awt.Dimension(673, 496));

        ScoreTextArea.setColumns(20);
        ScoreTextArea.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        ScoreTextArea.setRows(5);
        jScrollPane6.setViewportView(ScoreTextArea);

        WinLabel.setFont(new java.awt.Font("DejaVu Sans Light", 1, 12)); // NOI18N

        jButton1.setText("ESCI DAL GIOCO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setIcon(new javax.swing.ImageIcon("src\\main\\java\\\\img\\score.jpg"));

        HomeButton_Score.setText("HOME");
        HomeButton_Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton_ScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ScoreJFrameLayout = new javax.swing.GroupLayout(ScoreJFrame.getContentPane());
        ScoreJFrame.getContentPane().setLayout(ScoreJFrameLayout);
        ScoreJFrameLayout.setHorizontalGroup(
            ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreJFrameLayout.createSequentialGroup()
                .addGroup(ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScoreJFrameLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScoreJFrameLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ScoreJFrameLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(HomeButton_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ScoreJFrameLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)))
        );
        ScoreJFrameLayout.setVerticalGroup(
            ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreJFrameLayout.createSequentialGroup()
                .addComponent(WinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(ScoreJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ScoreJFrameLayout.createSequentialGroup()
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        SavesJFrame.setMinimumSize(new java.awt.Dimension(623, 417));

        SavesTextArea.setColumns(20);
        SavesTextArea.setRows(5);
        jScrollPane7.setViewportView(SavesTextArea);

        AvviaJButton.setText("Avvia");
        AvviaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvviaJButtonActionPerformed(evt);
            }
        });

        HomeButton_Saves.setText("Home");
        HomeButton_Saves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButton_SavesActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setIcon(new javax.swing.ImageIcon("src\\main\\java\\\\img\\saves.jpg"));

        javax.swing.GroupLayout SavesJFrameLayout = new javax.swing.GroupLayout(SavesJFrame.getContentPane());
        SavesJFrame.getContentPane().setLayout(SavesJFrameLayout);
        SavesJFrameLayout.setHorizontalGroup(
            SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavesJFrameLayout.createSequentialGroup()
                .addGroup(SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SavesJFrameLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SavesJFrameLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(SaveField, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SavesJFrameLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(HomeButton_Saves, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(AvviaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
        );
        SavesJFrameLayout.setVerticalGroup(
            SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SavesJFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaveField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvviaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeButton_Saves, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(SavesJFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(623, 417));
        setSize(new java.awt.Dimension(623, 417));

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        SavesButton.setText("Salvataggi");
        SavesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavesButtonActionPerformed(evt);
            }
        });

        SviluppatoriButton.setText("Sviluppatori");
        SviluppatoriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SviluppatoriButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("DejaVu Sans Light", 1, 18)); // NOI18N
        jTextField1.setText("Inserisci il Nickname");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ID);

        RulesButton.setText("Regole");
        RulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RulesButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Scores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\home.jpg"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SviluppatoriButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SavesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(127, 127, 127))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SavesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SviluppatoriButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
          
        // TODO add your handling code here:
        String a;
        a=ID.getText();
        if(a == null || a.equals("") ){
            JOptionPane.showMessageDialog(this, "Devi inserire il Nickname " ," INSERIRE NICKNAME", JOptionPane.ERROR_MESSAGE);
            
        }else{
              Giocatore = new Player(a);
             
             Nickname.setText(Giocatore.getNickname());
             this.setVisible(false);
             GameJFrame.setVisible(true);
             jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
             TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
             TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
        }
        
      
     
    }//GEN-LAST:event_playButtonActionPerformed

    private void NordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NordButtonActionPerformed
        // TODO add your handling code here:
        Giocatore.addPassi();
        if(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaNord() == -1){
            String b;
            b = noRoom();
            TextAreaGame.append(b+"\n");
        }else{
            Giocatore.setstanzaCorrente(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaNord());
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
           jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
         
        }
        
    }//GEN-LAST:event_NordButtonActionPerformed

    private void HomeButton_TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton_TutorialActionPerformed
        // TODO add your handling code here:
        TutorialJFrame.setVisible(false);
        TutorialTextArea.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_HomeButton_TutorialActionPerformed

    private void RulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RulesButtonActionPerformed
          this.setVisible(false);
          int i;
      
          for(i=0;i<row_regole;i++){
              TutorialTextArea.append(regole[i]+"\n");
          }

          
          TutorialJFrame.setVisible((true));
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RulesButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        CreatorsJFrame.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void TextFieldGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldGameActionPerformed

    private void SudButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SudButtonActionPerformed
        // TODO add your handling code here:
        Giocatore.addPassi();
         if(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaSud() == -1){
            String b;
            b = noRoom();
            TextAreaGame.append(b+"\n");
        }else{
            Giocatore.setstanzaCorrente(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaSud());
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
           jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
         }
    }//GEN-LAST:event_SudButtonActionPerformed

    private void EstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstButtonActionPerformed
        // TODO add your handling code here:
        Giocatore.addPassi();
         if(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaEst() == -1){
            String b;
            b = noRoom();
            TextAreaGame.append(b+"\n");
        }else{
            Giocatore.setstanzaCorrente(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaEst());
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
           jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
        }
    }//GEN-LAST:event_EstButtonActionPerformed

    private void OvestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OvestButtonActionPerformed
        // TODO add your handling code here:
        Giocatore.addPassi();
         if(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaOvest() == -1){
            String b;
            b = noRoom();
            TextAreaGame.append(b+"\n");
        }else{
            Giocatore.setstanzaCorrente(Stanze.get(Giocatore.getStanzaCorrente()).getIdStanzaOvest());
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
            jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
            
            
        }
    }//GEN-LAST:event_OvestButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void TakeiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TakeiButtonActionPerformed
         // TODO add your handling code here:
             Iterator<Oggetto> iterator = lista_items.iterator();
             int f=0;
             
      
             while(iterator.hasNext()){
                Oggetto item = iterator.next();
                 
                 
             if (item.getStanza() == Giocatore.getStanzaCorrente()) {
                 if(item.isPrendibile()){
                     item.deleteOgg();
                     Giocatore.addInventario(item);
                   
                   TextAreaGame.append("L'oggetto "+item.getName()+" e' stato inserito nell'inventario \n");
                   f=2;
             
                 }else{
                     f=1;
                 }
                 
             }
              }  
             if(f==0){
          TextAreaGame.append("Non c'e' alcun oggetto in questa stanza!  \n");
             
            }else{
                 if(f==1){
                     TextAreaGame.append("Non e' possibile prendere l'oggetto nella stanza, trova un modo!  \n");
                 }
                 
             }
             
    }//GEN-LAST:event_TakeiButtonActionPerformed

    private void InventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryButtonActionPerformed
        // TODO add your handling code here:
        Iterator<Oggetto> iterator = Giocatore.getInventario().getOggetti().iterator();
        TextAreaGame.append("Inventario:\n");
        int i=1;
        int f=0;
        if(iterator.hasNext()== false){
            TextAreaGame.append("Inventario vuoto");
            f=1;
        }
        while(iterator.hasNext()){
                Oggetto item = iterator.next();
             
                TextAreaGame.append(i+". "+ item.getName()+" : \n"+item.getDescription()+"\n"+item.getDescrUso()+"\n");
                i++;
        }
        if(f==0){
           TextAreaGame.append("Indicare il numero dell'oggetto che si vuole usare sulla riga qui sotto e premere Usa.\n");
        }
       
    }//GEN-LAST:event_InventoryButtonActionPerformed

    private void UseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseButtonActionPerformed
        // TODO add your handling code here:
        String input_text = TextFieldGame.getText();
      try{
    
         int index_ogg=Integer.parseInt(input_text);
         Iterator<Oggetto> iterator = Giocatore.getInventario().getOggetti().iterator();
         int i=1;
         int f=0;
         if(iterator.hasNext()== false){
            TextAreaGame.append("Inventario vuoto\n");
            
        }
         while(iterator.hasNext()){
                Oggetto item = iterator.next();
                if(i==index_ogg){
                    if(item.isUsabile()){
                        if(item.getIdOggetto() == finalr.getIdOggChiave()){
                        GameJFrame.setVisible(false);
                        FinalRoomJFrame.setVisible(true);
                        FinalTextArea.append(finalr.getDescrizione()+"\n");
                        FinalTextArea.append(finalr.getIndovinello()+"\n");
                        FinalTextArea.append("Inserire la Soluzione in minuscolo: \n");
                        NicknameFinal.setText(Giocatore.getNickname());

                       }
                    }else{
                        TextAreaGame.append("Non e' possibile usare l'oggetto al momento \n");
                    }
                    
                   
                }else{
                    TextAreaGame.append("Non esiste nell'inventario l'oggetto n."+index_ogg+" \n");
                }
         
             
               
        }
    
     }catch (NumberFormatException nfe) {
   
       TextAreaGame.append("L'elemento inserito non e' un numero utilizzabile,\n inserire il numero dell'oggetto che vuoi usare.\n");
    }
     
        
        TextFieldGame.setText("");
    }//GEN-LAST:event_UseButtonActionPerformed

    private void FinalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalButtonActionPerformed
        // TODO add your handling code here:
        if(FinalInput.getText().equals(finalr.getSoluzione())){
           
            Score score= new Score(Giocatore.getPassi(),7);
            try {
                InsertScore(Giocatore.getNickname(),score.getScore());
                FinalRoomJFrame.setVisible(false);
                HomeButton_Score.setVisible(false);
                ScoreJFrame.setVisible(true);
                WinLabel.setText("HAI VINTO!");
                GetScores();
            } catch (SQLException ex) {
                Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
            }
{
            
        }
        }else{
            FinalTextArea.append("SBAGLIATO! Riprova\n");
            FinalTextArea.append(finalr.getIndovinello()+"\n");
            FinalInput.setText("");
        }
    }//GEN-LAST:event_FinalButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);   
        ScoreJFrame.setVisible(true);
        GetScores();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SavesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavesButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        SavesJFrame.setVisible(true);
         try {
             Salvataggi();
         } catch (IOException | ClassNotFoundException ex) {
             Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_SavesButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        boolean salva;
        salva= salvaGiocatore(Giocatore);
        if(salva==true){
            TextAreaGame.append("Salvataggio riuscito! \n");
        }else{
            TextAreaGame.append("Salvataggio non riuscito! \n");
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void AvviaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvviaJButtonActionPerformed
        // TODO add your handling code here:
        String input_text = SaveField.getText();
        boolean verifica_save;
      try{
    
         int index_save=Integer.parseInt(input_text);
         verifica_save = PreparaSalvataggio(index_save);
         if(verifica_save==true){
            Giocatore = CaricaSalvataggio(index_save);
            
         Iterator<Oggetto> iterator = Giocatore.getInventario().getOggetti().iterator();
            while(iterator.hasNext()){
                 Oggetto item = iterator.next();
                 Iterator<Oggetto> iterator2 = lista_items.iterator();
             int f=0;
             
      
             while(iterator2.hasNext()){
                Oggetto item2= iterator2.next();
                 
               if (item2.getIdOggetto()== item.getIdOggetto() ) {
                   item2.setStanza(item.getStanza());
                   item2.setPrendibile(item.isPrendibile());
                   item2.setUsabile(item.isUsabile());
                }
               
              }
            }
            SavesJFrame.setVisible(false);
            GameJFrame.setVisible(true);
            Nickname.setText(Giocatore.getNickname());
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getNome()+"\n");
            TextAreaGame.append(Stanze.get(Giocatore.getStanzaCorrente()).getDescrizione()+"\n");
            jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\img\\stanza"+Giocatore.getStanzaCorrente()+".jpg"));
         
            
   
        }
     }catch (NumberFormatException nfe) {
   
       SavesTextArea.append("L'elemento inserito non e' un numero utilizzabile,\n inserire il numero del salvataggio che vuoi usare.\n");
    }    catch (IOException ex) {
             Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_AvviaJButtonActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        // TODO add your handling code here:
        String help = Help();
        TextAreaGame.append(help+"\n");
        
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void SviluppatoriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SviluppatoriButtonActionPerformed
       
             // TODO add your handling code here:
             this.setVisible(false);
             CreatorsJFrame.setVisible(true);
             takeThread svil = new takeThread();
        
    }//GEN-LAST:event_SviluppatoriButtonActionPerformed

    private void HomeButton_ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton_ScoreActionPerformed
        // TODO add your handling code here:
        ScoreJFrame.setVisible(false);
        ScoreTextArea.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_HomeButton_ScoreActionPerformed

    private void FinalInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalInputActionPerformed

    private void HomeButton_SavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButton_SavesActionPerformed
        // TODO add your handling code here:
        SavesJFrame.setVisible(false);
        SavesTextArea.setText("");
        this.setVisible(true);
    }//GEN-LAST:event_HomeButton_SavesActionPerformed
      
    
    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
           
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
                       
            @Override
            public void run() {
                try {
                    new SwingMain().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SwingMain.class.getName()).log(Level.SEVERE, null, ex);
                } 
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AvviaJButton;
    private javax.swing.JFrame CreatorsJFrame;
    private javax.swing.JButton EstButton;
    private javax.swing.JButton FinalButton;
    private javax.swing.JTextField FinalInput;
    private javax.swing.JFrame FinalRoomJFrame;
    private javax.swing.JTextArea FinalTextArea;
    private javax.swing.JFrame GameJFrame;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JButton HomeButton_Saves;
    private javax.swing.JButton HomeButton_Score;
    private javax.swing.JButton HomeButton_Tutorial;
    private javax.swing.JTextPane ID;
    private javax.swing.JButton InventoryButton;
    private javax.swing.JLabel Nickname;
    private javax.swing.JLabel NicknameFinal;
    private javax.swing.JButton NordButton;
    private javax.swing.JButton OvestButton;
    private javax.swing.JButton RulesButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SaveField;
    private javax.swing.JButton SavesButton;
    private javax.swing.JFrame SavesJFrame;
    public static javax.swing.JTextArea SavesTextArea;
    private javax.swing.JFrame ScoreJFrame;
    public static javax.swing.JTextArea ScoreTextArea;
    private javax.swing.JButton SudButton;
    public static javax.swing.JLabel Sviluppatore;
    private javax.swing.JButton SviluppatoriButton;
    private javax.swing.JButton TakeiButton;
    private javax.swing.JTextArea TextAreaGame;
    private static javax.swing.JTextField TextFieldGame;
    private javax.swing.JFrame TutorialJFrame;
    private javax.swing.JTextArea TutorialTextArea;
    private javax.swing.JButton UseButton;
    private javax.swing.JLabel WinLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton playButton;
    // End of variables declaration//GEN-END:variables
}
